#ifndef SDK_FEATURE_TOOLSET_FEATURES_LAUFWERK_SSD_H_
#define SDK_FEATURE_TOOLSET_FEATURES_LAUFWERK_SSD_H_

#include "feature.h"

class SSD : public Feature
{
};

#endif // SDK_FEATURE_TOOLSET_FEATURES_LAUFWERK_SSD_H_
